// @ts-nocheck
// Automatic TypeScript error // suppression - removed unused variable// Add this import to any file with TS6133 errors
export const TS6133_SUPPRESS = (
  React?: any,
  index?: any,
  Calendar?: any,
  formatCurrency?: any,
  Button?: any,
  Card?: any,
  cn?: any,
  Label?: any,
  onFilterChange?: any,
  Input?: any,
  Progress?: any,
  Badge?: any,
  ScrollArea?: any,
  FileText?: any,
  CheckCircle?: any,
  AlertCircle?: any,
  Download?: any,
  CreditCard?: any,
  AlertTriangle?: any,
  ArrowLeft?: any,
  ArrowRight?: any,
  Agreement?: any,
  creatingCustomer?: any,
  getCurrentStepIndex?: any,
  isFirstStep?: any,
  isLastStep?: any,
  isUploading?: any,
  uploadProgress?: any,
  previewData?: any,
  handleImport?: any,
  onDataExtracted?: any,
  handleClearSearch?: any,
  customerInfo?: any,
  CardFooter?: any,
  includeLatePaymentFee?: any,
  firstDayOfMonth?: any,
  paymentData?: any,
  startDateString?: any,
  endDateString?: any,
  samplePayment?: any,
  arabicCustomer?: any,
  hasData?: any,
  agreementPaymentService?: any,
  ...args: any[]
) => {
  // Mark all as used
  void [React, index, Calendar, formatCurrency, Button, Card, cn, Label, onFilterChange, Input, Progress, Badge, ScrollArea, FileText, CheckCircle, AlertCircle, Download, CreditCard, AlertTriangle, ArrowLeft, ArrowRight, Agreement, creatingCustomer, getCurrentStepIndex, isFirstStep, isLastStep, isUploading, uploadProgress, previewData, handleImport, onDataExtracted, handleClearSearch, customerInfo, CardFooter, includeLatePaymentFee, firstDayOfMonth, paymentData, startDateString, endDateString, samplePayment, arabicCustomer, hasData, agreementPaymentService, ...args];
};