
project_id = "vqdlsidkucrownbfuouq"

[functions.validate-traffic-fine]
verify_jwt = true

[functions.process-customer-imports]
verify_jwt = true

[functions.process-agreement-imports]
verify_jwt = true
