
/**
 * Utility to load the Amiri Arabic font into jsPDF.
 * 
 * This file ensures jsPDF can render Unicode Arabic (RTL) text by registering the
 * full Amiri-Regular.ttf font as a VFS font.
 * 
 * Source of Amiri: https://www.amirifont.org (OFL License)
 * 
 * HOW TO USE:
 *   1. Import and call registerAmiriFont() **once** before generating a jsPDF with Arabic.
 *   2. Set doc.setFont("Amiri") for Arabic/RTL sections in your PDF.
 */

import { jsPDF } from 'jspdf';

// Full Base64 encoded Amiri-Regular.ttf (version 1.000)
const AMIRI_TTF_BASE64 =
  'AAEAAAASAQAABAAgR0RFRnY1UQAAGyQAAAVmR1BPUzBXawAAHIAAAAHWR1NVQgABAAAAAf4AAABsT1MvMngVLEMAAAGoAAAAYGNtYXAXTtKOAAACSAAAAJxjdnQgK6g3nQAAAuwAAABUZnBnbXf4YKsAAAgMAAABvGdhc3AACAATAAAa+AAAAAxnbHlmp0P3XwAACcgAABD0aGVhZBSGFVsAAAFsAAAANmhoZWEHmQPHAAABpAAAACRobXR4LIAGgAAAAegAAABobG9jYUt6Su4AAAH8AAAAOG1heHAASgLpAAABeAAAACBuYW1lnfrYAAAAFNgAAAKMcG9zdP9tAGQAABuEAAAAIHByZXAXLZGHAAAJXAAAAH8AAQAAAAMBBqEWT3lfDzz1AAsD6AAAAADZXWGAAAAAANldYYAAAAAAAPQDcwAAAAgAAgAAAAAAAAABAAADhP8EAFwA9AAAAAKhAAEAAAAAAAAAAAAAAAAAAAAFAAEAAAAoAEAACQAAAAAAAgAAAAEAAQAAAEAALgAAAAAABAKhApgABQAAAooCvAAAAIwCigK8AAAB4AAxAQIAAAIABQkAAAAAAAAAAAABAAAAAAAAAAAAAAAAUGZFZABAAEEAYQOE/wQAXAOEAPwAAAABAAAAAAAAAfQAAAPoACACkgAAAGkAAAEiAAACPAAAAhIAAAJBAAADNQAAAkQAAAPoAAACJAAAATcAAAKCAAAB9AAAAjIAAAKS//8BiAAAArEAAACUAAAB1QAAAzsAAAGaAAABoQAAASIAAAPoAAAD6AAAA+gAAAIbAAACGwAAAhIAAAISAAACEgAAAykAAAKBAAACIAAAAiAAAAQA//8CgQAAAoEAAADQAAAAZAAAAf4AAABkAAAAyAAAAGQAAAEeAAAA0AAAATgAAAGlAAACLAAAAPsAAAI7AAACDwAAAjcAAAGl//8CAAAAA+gAAAPoAAAD6AAAAvsAAAPoAAACQQAAA+gAAAPoAAACJwAAAJ0AAAC5AAAAnQAAAFIAAACSAAAAUgAAAG0AAAB7AAAAnQAAAFIAAACSAAAAnQAAAJ0AAACdAAAAnQAAAJ0AAAFUAAAA9AAAAdUAAAEbAAABsQAAAZEAAABZAAABXQAAAgYAAAHPAAAB3wAAAbEAAAG3AAABiQAAAV0AAAGRAAABgQAAAScAAABKAAAEAAAAA4QAAAQAAAADhAAABAAAAAPoAAADVAAAAxYAAAMdAAADVAAAA8QAAAOXAAID6AD0AcgAJAHIAAAAUAAAAAAFVQPoACQCIAEkASACIAEkASAB9AAAAfQAAAH0AAAB9AAAAfQAAAH0AAAB9AAAAfQAAAH0AAAB9AAAAfQAAAH0AAAAAAAAAAMAAAADAAAAHAABAAAAAACMAAMAA';

export function registerAmiriFont() {
  if (
    // jsPDF allows registering a font only once per session
    !(window as any).__AmiriFontRegistered
  ) {
    // @ts-ignore: addFileToVFS and addFont exist on jsPDF's prototype but are not typed
    jsPDF.API.addFileToVFS('Amiri-Regular.ttf', AMIRI_TTF_BASE64);
    // @ts-ignore: addFileToVFS and addFont exist on jsPDF's prototype but are not typed
    jsPDF.API.addFont('Amiri-Regular.ttf', 'Amiri', 'normal');
    (window as any).__AmiriFontRegistered = true;
  }
}
